#!/bin/bash

export __scriptpath=$(cd $(dirname $0) && pwd)
export __rootdir=$(dirname ${__scriptpath}/..)
export __logdir=/var/tmp/nvim_log

# 打包
cd ${__rootdir}

exec /usr/bin/python  ${__scriptpath}/hack.py $*
